class AppL10n {
  final String languageCode;
  const AppL10n(this.languageCode);

  static const AppL10n _ko = AppL10n('ko');
  static const AppL10n _en = AppL10n('en');
  static const AppL10n _ja = AppL10n('ja');
  static const AppL10n _zh = AppL10n('zh');
  static const AppL10n _fr = AppL10n('fr');
  static const AppL10n _de = AppL10n('de');
  static const AppL10n _es = AppL10n('es');
  static const AppL10n _pt = AppL10n('pt');
  static const AppL10n _ru = AppL10n('ru');
  static const AppL10n _tr = AppL10n('tr');
  static const AppL10n _ar = AppL10n('ar');
  static const AppL10n _it = AppL10n('it');
  static const AppL10n _hi = AppL10n('hi');
  static const AppL10n _th = AppL10n('th');

  static AppL10n of(String code) {
    switch (code) {
      case 'ko': return _ko;
      case 'ja': return _ja;
      case 'zh': return _zh;
      case 'fr': return _fr;
      case 'de': return _de;
      case 'es': return _es;
      case 'pt': return _pt;
      case 'ru': return _ru;
      case 'tr': return _tr;
      case 'ar': return _ar;
      case 'it': return _it;
      case 'hi': return _hi;
      case 'th': return _th;
      default: return _en;
    }
  }

  String _t(Map<String, String> translations) =>
      translations[languageCode] ?? translations['en'] ?? '';

  // ── App-wide ──────────────────────────────────────────────────────────────
  String get appName => _t({'ko': 'Message in a Bottle', 'en': 'Message in a Bottle', 'ja': 'メッセージ・イン・ア・ボトル', 'zh': '漂流瓶信', 'fr': 'Message dans une bouteille', 'de': 'Flaschenpost', 'es': 'Mensaje en una botella', 'pt': 'Mensagem numa garrafa', 'ru': 'Письмо в бутылке', 'tr': 'Şişedeki Mesaj', 'ar': 'رسالة في زجاجة', 'it': 'Messaggio in bottiglia', 'hi': 'बोतल में संदेश', 'th': 'ข้อความในขวด'});

  String get tagline => _t({'ko': '세상 어딘가의 당신에게', 'en': 'To you, somewhere in the world', 'ja': 'どこかの誰かへ', 'zh': '致世界某处的你', 'fr': 'À toi, quelque part dans le monde', 'de': 'An dich, irgendwo auf der Welt', 'es': 'A ti, en algún lugar del mundo', 'pt': 'Para você, em algum lugar do mundo', 'ru': 'Тебе, где-то в мире', 'tr': 'Dünyanın bir yerindeki sana', 'ar': 'إليك، في مكان ما في العالم', 'it': 'A te, da qualche parte nel mondo', 'hi': 'दुनिया में कहीं तुम्हारे लिए', 'th': 'ถึงคุณ ที่ไหนสักแห่งในโลก'});

  // ── Auth ──────────────────────────────────────────────────────────────────
  String get login => _t({'ko': '로그인', 'en': 'Login', 'ja': 'ログイン', 'zh': '登录', 'fr': 'Connexion', 'de': 'Anmelden', 'es': 'Iniciar sesión', 'pt': 'Entrar', 'ru': 'Войти', 'tr': 'Giriş yap', 'ar': 'تسجيل الدخول', 'it': 'Accedi', 'hi': 'लॉगिन', 'th': 'เข้าสู่ระบบ'});
  String get signup => _t({'ko': '회원가입', 'en': 'Sign Up', 'ja': '新規登録', 'zh': '注册', 'fr': "S'inscrire", 'de': 'Registrieren', 'es': 'Registrarse', 'pt': 'Cadastrar', 'ru': 'Зарегистрироваться', 'tr': 'Üye ol', 'ar': 'إنشاء حساب', 'it': 'Registrati', 'hi': 'साइनअप', 'th': 'สมัครสมาชิก'});
  String get email => _t({'ko': '이메일', 'en': 'Email', 'ja': 'メール', 'zh': '邮箱', 'fr': 'Email', 'de': 'E-Mail', 'es': 'Correo', 'pt': 'Email', 'ru': 'Email', 'tr': 'E-posta', 'ar': 'البريد الإلكتروني', 'it': 'Email', 'hi': 'ईमेल', 'th': 'อีเมล'});
  String get password => _t({'ko': '비밀번호', 'en': 'Password', 'ja': 'パスワード', 'zh': '密码', 'fr': 'Mot de passe', 'de': 'Passwort', 'es': 'Contraseña', 'pt': 'Senha', 'ru': 'Пароль', 'tr': 'Şifre', 'ar': 'كلمة المرور', 'it': 'Password', 'hi': 'पासवर्ड', 'th': 'รหัสผ่าน'});
  String get username => _t({'ko': '사용자 이름', 'en': 'Username', 'ja': 'ユーザー名', 'zh': '用户名', 'fr': "Nom d'utilisateur", 'de': 'Benutzername', 'es': 'Nombre de usuario', 'pt': 'Nome de usuário', 'ru': 'Имя пользователя', 'tr': 'Kullanıcı adı', 'ar': 'اسم المستخدم', 'it': 'Nome utente', 'hi': 'उपयोगकर्ता नाम', 'th': 'ชื่อผู้ใช้'});
  String get selectCountry => _t({'ko': '나라 선택', 'en': 'Select Country', 'ja': '国を選択', 'zh': '选择国家', 'fr': 'Choisir le pays', 'de': 'Land auswählen', 'es': 'Seleccionar país', 'pt': 'Selecionar país', 'ru': 'Выберите страну', 'tr': 'Ülke seç', 'ar': 'اختر الدولة', 'it': 'Seleziona paese', 'hi': 'देश चुनें', 'th': 'เลือกประเทศ'});

  // ── Privacy policy ────────────────────────────────────────────────────────
  String get agreePrivacy => _t({'ko': '개인정보 처리방침에 동의합니다', 'en': 'I agree to the Privacy Policy', 'ja': 'プライバシーポリシーに同意します', 'zh': '我同意隐私政策', 'fr': "J'accepte la politique de confidentialité", 'de': 'Ich stimme der Datenschutzrichtlinie zu', 'es': 'Acepto la política de privacidad', 'pt': 'Concordo com a Política de Privacidade', 'ru': 'Я соглашаюсь с политикой конфиденциальности', 'tr': 'Gizlilik Politikasını kabul ediyorum', 'ar': 'أوافق على سياسة الخصوصية', 'it': "Accetto l'informativa sulla privacy", 'hi': 'मैं गोपनीयता नीति से सहमत हूं', 'th': 'ฉันยอมรับนโยบายความเป็นส่วนตัว'});

  String get languageNotice => _t({'ko': '선택한 나라의 언어로 앱이 표시됩니다', 'en': 'The app will be displayed in your country\'s language', 'ja': '選択した国の言語でアプリが表示されます', 'zh': '应用将以所选国家的语言显示', 'fr': "L'application sera affichée dans la langue de votre pays", 'de': 'Die App wird in der Sprache Ihres Landes angezeigt', 'es': 'La aplicación se mostrará en el idioma de su país', 'pt': 'O aplicativo será exibido no idioma do seu país', 'ru': 'Приложение будет отображаться на языке вашей страны', 'tr': 'Uygulama ülkenizin dilinde görüntülenecek', 'ar': 'سيتم عرض التطبيق بلغة بلدك', 'it': "L'app verrà visualizzata nella lingua del tuo paese", 'hi': 'ऐप आपके देश की भाषा में प्रदर्शित होगा', 'th': 'แอปจะแสดงในภาษาของประเทศคุณ'});

  // ── Map ───────────────────────────────────────────────────────────────────
  String get map => _t({'ko': '지도', 'en': 'Map', 'ja': '地図', 'zh': '地图', 'fr': 'Carte', 'de': 'Karte', 'es': 'Mapa', 'pt': 'Mapa', 'ru': 'Карта', 'tr': 'Harita', 'ar': 'خريطة', 'it': 'Mappa', 'hi': 'नक्शा', 'th': 'แผนที่'});
  String get inbox => _t({'ko': '편지함', 'en': 'Inbox', 'ja': '受信箱', 'zh': '收件箱', 'fr': 'Boîte de réception', 'de': 'Posteingang', 'es': 'Bandeja de entrada', 'pt': 'Caixa de entrada', 'ru': 'Входящие', 'tr': 'Gelen kutusu', 'ar': 'البريد الوارد', 'it': 'Posta in arrivo', 'hi': 'इनबॉक्स', 'th': 'กล่องจดหมาย'});
  String get profile => _t({'ko': '프로필', 'en': 'Profile', 'ja': 'プロフィール', 'zh': '个人资料', 'fr': 'Profil', 'de': 'Profil', 'es': 'Perfil', 'pt': 'Perfil', 'ru': 'Профиль', 'tr': 'Profil', 'ar': 'الملف الشخصي', 'it': 'Profilo', 'hi': 'प्रोफ़ाइल', 'th': 'โปรไฟล์'});

  // ── Inbox ─────────────────────────────────────────────────────────────────
  String get received => _t({'ko': '받은 편지', 'en': 'Received', 'ja': '受信', 'zh': '已收到', 'fr': 'Reçus', 'de': 'Empfangen', 'es': 'Recibidos', 'pt': 'Recebidos', 'ru': 'Получено', 'tr': 'Alınanlar', 'ar': 'المستلمة', 'it': 'Ricevuti', 'hi': 'प्राप्त', 'th': 'ที่ได้รับ'});
  String get sent => _t({'ko': '보낸 편지', 'en': 'Sent', 'ja': '送信済み', 'zh': '已发送', 'fr': 'Envoyés', 'de': 'Gesendet', 'es': 'Enviados', 'pt': 'Enviados', 'ru': 'Отправлено', 'tr': 'Gönderilenler', 'ar': 'المرسلة', 'it': 'Inviati', 'hi': 'भेजे गए', 'th': 'ที่ส่งแล้ว'});
  String get translate => _t({'ko': '번역하기', 'en': 'Translate', 'ja': '翻訳する', 'zh': '翻译', 'fr': 'Traduire', 'de': 'Übersetzen', 'es': 'Traducir', 'pt': 'Traduzir', 'ru': 'Перевести', 'tr': 'Çevir', 'ar': 'ترجمة', 'it': 'Tradurre', 'hi': 'अनुवाद करें', 'th': 'แปล'});
  String get originalText => _t({'ko': '원문 보기', 'en': 'Original', 'ja': '原文を見る', 'zh': '查看原文', 'fr': 'Texte original', 'de': 'Originaltext', 'es': 'Texto original', 'pt': 'Texto original', 'ru': 'Оригинал', 'tr': 'Orijinal metin', 'ar': 'النص الأصلي', 'it': 'Testo originale', 'hi': 'मूल पाठ', 'th': 'ข้อความต้นฉบับ'});

  // ── Chain rule ────────────────────────────────────────────────────────────
  String get chainRuleLocked => _t({'ko': '다음 편지를 읽으려면 편지를 3개 보내야 합니다', 'en': 'Send 3 letters to unlock the next one', 'ja': '次の手紙を読むには3通送ってください', 'zh': '发送3封信后可阅读下一封', 'fr': 'Envoyez 3 lettres pour lire la suivante', 'de': 'Sende 3 Briefe um den nächsten zu lesen', 'es': 'Envía 3 cartas para leer la siguiente', 'pt': 'Envie 3 cartas para ler a próxima', 'ru': 'Отправьте 3 письма чтобы читать следующее', 'tr': 'Sonrakini okumak için 3 mektup gönder', 'ar': 'أرسل 3 رسائل لقراءة التالية', 'it': 'Invia 3 lettere per leggere la prossima', 'hi': 'अगली पढ़ने के लिए 3 पत्र भेजें', 'th': 'ส่ง 3 จดหมายเพื่ออ่านฉบับต่อไป'});

  // ── Compose ───────────────────────────────────────────────────────────────
  String get writeLetter => _t({'ko': '편지 쓰기', 'en': 'Write Letter', 'ja': '手紙を書く', 'zh': '写信', 'fr': 'Écrire une lettre', 'de': 'Brief schreiben', 'es': 'Escribir carta', 'pt': 'Escrever carta', 'ru': 'Написать письмо', 'tr': 'Mektup yaz', 'ar': 'كتابة رسالة', 'it': 'Scrivi lettera', 'hi': 'पत्र लिखें', 'th': 'เขียนจดหมาย'});
  String get sendLetter => _t({'ko': '편지 보내기', 'en': 'Send Letter', 'ja': '手紙を送る', 'zh': '发送信件', 'fr': 'Envoyer la lettre', 'de': 'Brief senden', 'es': 'Enviar carta', 'pt': 'Enviar carta', 'ru': 'Отправить письмо', 'tr': 'Mektup gönder', 'ar': 'إرسال الرسالة', 'it': 'Invia lettera', 'hi': 'पत्र भेजें', 'th': 'ส่งจดหมาย'});
  String get includeSns => _t({'ko': 'SNS 주소 포함하기', 'en': 'Include SNS link', 'ja': 'SNSを含める', 'zh': '包含SNS链接', 'fr': 'Inclure le lien SNS', 'de': 'SNS-Link einfügen', 'es': 'Incluir enlace SNS', 'pt': 'Incluir link SNS', 'ru': 'Включить ссылку SNS', 'tr': 'SNS bağlantısı ekle', 'ar': 'تضمين رابط SNS', 'it': 'Includi link SNS', 'hi': 'SNS लिंक शामिल करें', 'th': 'รวมลิงก์ SNS'});

  // ── Notification ──────────────────────────────────────────────────────────
  String get nearbyNotifTitle => _t({'ko': '📬 편지가 도착했어요!', 'en': '📬 A letter has arrived!', 'ja': '📬 手紙が届きました！', 'zh': '📬 信件已到达！', 'fr': '📬 Une lettre est arrivée!', 'de': '📬 Ein Brief ist angekommen!', 'es': '📬 ¡Ha llegado una carta!', 'pt': '📬 Uma carta chegou!', 'ru': '📬 Пришло письмо!', 'tr': '📬 Bir mektup geldi!', 'ar': '📬 وصلت رسالة!', 'it': '📬 È arrivata una lettera!', 'hi': '📬 एक पत्र आया है!', 'th': '📬 จดหมายมาถึงแล้ว!'});
  String get nearbyNotifBody => _t({'ko': '500m 이내에 편지가 있어요. 앱에서 확인하세요!', 'en': 'A letter is within 500m. Check it in the app!', 'ja': '500m以内に手紙があります。アプリで確認してください！', 'zh': '500米内有一封信。在应用中查看！', 'fr': 'Une lettre est à moins de 500m. Vérifiez dans l\'app!', 'de': 'Ein Brief ist weniger als 500m entfernt. In der App prüfen!', 'es': 'Hay una carta a menos de 500m. ¡Revísala en la app!', 'pt': 'Há uma carta a menos de 500m. Verifique no app!', 'ru': 'Письмо в 500м от вас. Проверьте в приложении!', 'tr': '500m içinde bir mektup var. Uygulamada kontrol et!', 'ar': 'توجد رسالة على بعد 500 متر. تحقق من التطبيق!', 'it': 'C\'è una lettera a meno di 500m. Controlla nell\'app!', 'hi': '500मी के भीतर एक पत्र है। ऐप में चेक करें!', 'th': 'มีจดหมายอยู่ภายใน 500ม. ตรวจสอบในแอป!'});

  // ── Delivery status ───────────────────────────────────────────────────────
  String get inTransit => _t({'ko': '배송 중', 'en': 'In Transit', 'ja': '配送中', 'zh': '运输中', 'fr': 'En transit', 'de': 'Unterwegs', 'es': 'En tránsito', 'pt': 'Em trânsito', 'ru': 'В пути', 'tr': 'Yolda', 'ar': 'في الطريق', 'it': 'In transito', 'hi': 'पारगमन में', 'th': 'กำลังส่ง'});
  String get delivered => _t({'ko': '배달 완료', 'en': 'Delivered', 'ja': '配達完了', 'zh': '已投递', 'fr': 'Livré', 'de': 'Zugestellt', 'es': 'Entregado', 'pt': 'Entregue', 'ru': 'Доставлено', 'tr': 'Teslim edildi', 'ar': 'تم التسليم', 'it': 'Consegnato', 'hi': 'डिलीवर हुआ', 'th': 'จัดส่งแล้ว'});
  String get read => _t({'ko': '읽음', 'en': 'Read', 'ja': '既読', 'zh': '已读', 'fr': 'Lu', 'de': 'Gelesen', 'es': 'Leído', 'pt': 'Lido', 'ru': 'Прочитано', 'tr': 'Okundu', 'ar': 'مقروء', 'it': 'Letto', 'hi': 'पढ़ा', 'th': 'อ่านแล้ว'});
  String get unread => _t({'ko': '미읽음', 'en': 'Unread', 'ja': '未読', 'zh': '未读', 'fr': 'Non lu', 'de': 'Ungelesen', 'es': 'No leído', 'pt': 'Não lido', 'ru': 'Непрочитанное', 'tr': 'Okunmadı', 'ar': 'غير مقروء', 'it': 'Non letto', 'hi': 'अपठित', 'th': 'ยังไม่ได้อ่าน'});

  // ── Onboarding ────────────────────────────────────────────────────────────
  String get onboarding1Title => _t({'ko': '🍾 메시지 인 어 보틀', 'en': '🍾 Message in a Bottle', 'ja': '🍾 メッセージ・イン・ア・ボトル', 'zh': '🍾 漂流瓶', 'fr': '🍾 Message dans une bouteille', 'de': '🍾 Flaschenpost', 'es': '🍾 Mensaje en una botella', 'pt': '🍾 Mensagem numa garrafa', 'ru': '🍾 Письмо в бутылке', 'tr': '🍾 Şişedeki Mesaj', 'ar': '🍾 رسالة في زجاجة', 'it': '🍾 Messaggio in bottiglia', 'hi': '🍾 बोतल में संदेश', 'th': '🍾 ข้อความในขวด'});
  String get onboarding1Body => _t({'ko': '세상 어딘가의 누군가에게 익명 편지를 보내세요. 실제 우편 배송 경로로 전달됩니다.', 'en': 'Send anonymous letters to someone, somewhere in the world. Delivered via real postal routes.', 'ja': '世界のどこかにいる誰かに匿名の手紙を送りましょう。実際の郵便ルートで届けられます。', 'zh': '向世界某处的某人发送匿名信。通过真实邮政路线递送。', 'fr': 'Envoyez des lettres anonymes à quelqu\'un quelque part dans le monde.', 'de': 'Sende anonyme Briefe an jemanden, irgendwo auf der Welt.', 'es': 'Envía cartas anónimas a alguien en algún lugar del mundo.', 'pt': 'Envie cartas anônimas para alguém em algum lugar do mundo.', 'ru': 'Отправляйте анонимные письма кому-то, где-то в мире.', 'tr': 'Dünyanın bir yerindeki birine anonim mektuplar gönderin.', 'ar': 'أرسل رسائل مجهولة إلى شخص ما في مكان ما في العالم.', 'it': 'Invia lettere anonime a qualcuno, da qualche parte nel mondo.', 'hi': 'दुनिया में कहीं किसी को अनाम पत्र भेजें।', 'th': 'ส่งจดหมายนิรนามถึงใครบางคนที่ไหนสักแห่งในโลก'});

  String get onboarding2Title => _t({'ko': '✈️ 실제 배송 경로', 'en': '✈️ Real Delivery Routes', 'ja': '✈️ リアルな配送ルート', 'zh': '✈️ 真实投递路线', 'fr': '✈️ Vraies routes de livraison', 'de': '✈️ Echte Lieferwege', 'es': '✈️ Rutas de entrega reales', 'pt': '✈️ Rotas de entrega reais', 'ru': '✈️ Реальные маршруты доставки', 'tr': '✈️ Gerçek teslimat güzergahları', 'ar': '✈️ مسارات التسليم الحقيقية', 'it': '✈️ Percorsi di consegna reali', 'hi': '✈️ वास्तविक डिलीवरी रूट', 'th': '✈️ เส้นทางการส่งจดหมายจริง'});
  String get onboarding2Body => _t({'ko': '편지는 트럭 🚚 → 공항 ✈️ → 목적지 트럭 🚚 순서로 세계지도에서 이동합니다. 실제 우편 시간을 반영합니다.', 'en': 'Letters travel 🚚 → ✈️ → 🚚 on a world map, reflecting real postal delivery times.', 'ja': '手紙は🚚→✈️→🚚の順で世界地図を移動します。実際の郵便時間を反映します。', 'zh': '信件在世界地图上沿🚚→✈️→🚚路线移动，反映真实邮递时间。', 'fr': 'Les lettres voyagent 🚚→✈️→🚚 sur la carte du monde, reflétant les délais postaux réels.', 'de': 'Briefe reisen 🚚→✈️→🚚 auf der Weltkarte, entsprechend echter Postzeiten.', 'es': 'Las cartas viajan 🚚→✈️→🚚 en el mapa del mundo, reflejando tiempos postales reales.', 'pt': 'As cartas viajam 🚚→✈️→🚚 no mapa mundial, refletindo tempos postais reais.', 'ru': 'Письма путешествуют 🚚→✈️→🚚 на карте мира, отражая реальные сроки доставки.', 'tr': 'Mektuplar dünya haritasında 🚚→✈️→🚚 seyahat eder, gerçek posta sürelerini yansıtır.', 'ar': 'تسافر الرسائل 🚚→✈️→🚚 على الخريطة العالمية، مما يعكس أوقات البريد الحقيقية.', 'it': 'Le lettere viaggiano 🚚→✈️→🚚 sulla mappa del mondo, riflettendo i tempi postali reali.', 'hi': 'पत्र विश्व मानचित्र पर 🚚→✈️→🚚 यात्रा करते हैं, वास्तविक डाक समय को दर्शाते हैं।', 'th': 'จดหมายเดินทาง 🚚→✈️→🚚 บนแผนที่โลก สะท้อนเวลาส่งไปรษณีย์จริง'});

  String get onboarding3Title => _t({'ko': '📬 편지 교환 규칙', 'en': '📬 Letter Exchange Rules', 'ja': '📬 手紙交換ルール', 'zh': '📬 信件交换规则', 'fr': '📬 Règles d\'échange de lettres', 'de': '📬 Briefaustauschregeln', 'es': '📬 Reglas de intercambio de cartas', 'pt': '📬 Regras de troca de cartas', 'ru': '📬 Правила обмена письмами', 'tr': '📬 Mektup alışverişi kuralları', 'ar': '📬 قواعد تبادل الرسائل', 'it': '📬 Regole di scambio lettere', 'hi': '📬 पत्र विनिमय नियम', 'th': '📬 กฎการแลกจดหมาย'});
  String get onboarding3Body => _t({'ko': '편지를 3개 보내야 다음 받은 편지를 읽을 수 있어요. 공정한 교환을 통해 모두가 편지를 받을 수 있습니다!', 'en': 'You must send 3 letters before reading the next received one. Fair exchange keeps letters flowing for everyone!', 'ja': '次の受信した手紙を読む前に3通送る必要があります。公平な交換でみんなに手紙が届きます！', 'zh': '阅读下一封收到的信件前，必须发送3封信。公平交换，让每个人都能收到信！', 'fr': 'Vous devez envoyer 3 lettres avant de lire la suivante. L\'échange équitable garde les lettres en circulation!', 'de': 'Sie müssen 3 Briefe senden, bevor Sie den nächsten lesen. Fairer Austausch hält Briefe für alle fließen!', 'es': 'Debes enviar 3 cartas antes de leer la siguiente recibida. ¡El intercambio justo mantiene las cartas fluyendo para todos!', 'pt': 'Você deve enviar 3 cartas antes de ler a próxima recebida. Troca justa mantém as cartas fluindo para todos!', 'ru': 'Вы должны отправить 3 письма, прежде чем прочитать следующее. Справедливый обмен держит письма в движении!', 'tr': 'Bir sonrakini okumadan önce 3 mektup göndermeniz gerekiyor. Adil değişim mektupları herkes için akıyor tutar!', 'ar': 'يجب عليك إرسال 3 رسائل قبل قراءة التالية. التبادل العادل يبقي الرسائل تتدفق للجميع!', 'it': 'Devi inviare 3 lettere prima di leggere la prossima ricevuta. Lo scambio equo mantiene le lettere in circolazione per tutti!', 'hi': 'अगली प्राप्त पत्र पढ़ने से पहले 3 पत्र भेजने होंगे। उचित विनिमय सभी के लिए पत्र प्रवाहित रखता है!', 'th': 'คุณต้องส่งจดหมาย 3 ฉบับก่อนอ่านฉบับถัดไปที่ได้รับ การแลกเปลี่ยนที่เป็นธรรมทำให้จดหมายไหลเวียนสำหรับทุกคน!'});

  String get onboarding4Title => _t({'ko': '🌗 시간대별 화면', 'en': '🌗 Time-Based Themes', 'ja': '🌗 時間帯のテーマ', 'zh': '🌗 时间主题', 'fr': '🌗 Thèmes selon l\'heure', 'de': '🌗 Zeitbasierte Designs', 'es': '🌗 Temas según la hora', 'pt': '🌗 Temas baseados na hora', 'ru': '🌗 Темы по времени суток', 'tr': '🌗 Saate göre temalar', 'ar': '🌗 مظاهر حسب الوقت', 'it': '🌗 Temi basati sull\'ora', 'hi': '🌗 समय-आधारित थीम', 'th': '🌗 ธีมตามเวลา'});
  String get onboarding4Body => _t({'ko': '앱 화면이 내 나라의 현재 시간에 맞춰 낮☀️, 저녁🌅, 밤🌙으로 자동 변경됩니다.', 'en': 'The app automatically changes to morning☀️, evening🌅, or night🌙 based on your country\'s local time.', 'ja': 'アプリは自国の現地時刻に合わせて朝☀️・夕方🌅・夜🌙に自動変更されます。', 'zh': '应用根据您所在国家的当地时间自动切换为早晨☀️、傍晚🌅或夜晚🌙。', 'fr': "L'app change automatiquement en matin☀️, soir🌅, nuit🌙 selon l'heure locale de votre pays.", 'de': 'Die App wechselt automatisch zu Morgen☀️, Abend🌅 oder Nacht🌙 entsprechend der Ortszeit.', 'es': 'La app cambia automáticamente a mañana☀️, tarde🌅 o noche🌙 según la hora local de tu país.', 'pt': 'O app muda automaticamente para manhã☀️, tarde🌅 ou noite🌙 conforme a hora local.', 'ru': 'Приложение автоматически меняется на утро☀️, вечер🌅 или ночь🌙 по местному времени.', 'tr': 'Uygulama ülkenizin yerel saatine göre otomatik olarak sabah☀️, akşam🌅 veya gece🌙ya dönüşür.', 'ar': 'يتغير التطبيق تلقائياً إلى صباح☀️ أو مساء🌅 أو ليل🌙 حسب التوقيت المحلي لبلدك.', 'it': "L'app cambia automaticamente in mattina☀️, sera🌅 o notte🌙 in base all'ora locale.", 'hi': 'ऐप स्वचालित रूप से आपके देश के स्थानीय समय के अनुसार सुबह☀️, शाम🌅 या रात🌙 में बदल जाता है।', 'th': 'แอปเปลี่ยนเป็นเช้า☀️ เย็น🌅 หรือกลางคืน🌙 โดยอัตโนมัติตามเวลาท้องถิ่นของประเทศคุณ'});

  String get onboarding5Title => _t({'ko': '🚀 시작하기', 'en': '🚀 Get Started', 'ja': '🚀 始めましょう', 'zh': '🚀 开始', 'fr': '🚀 Commencer', 'de': '🚀 Loslegen', 'es': '🚀 Comenzar', 'pt': '🚀 Começar', 'ru': '🚀 Начать', 'tr': '🚀 Başla', 'ar': '🚀 ابدأ', 'it': '🚀 Inizia', 'hi': '🚀 शुरू करें', 'th': '🚀 เริ่มต้น'});
  String get onboarding5Body => _t({'ko': '지금 바로 가입하고 세계 어딘가의 누군가와 특별한 편지를 교환해 보세요!', 'en': 'Sign up now and start exchanging special letters with someone, somewhere in the world!', 'ja': '今すぐ登録して、世界のどこかにいる誰かと特別な手紙を交換しましょう！', 'zh': '立即注册，开始与世界某处的某人交换特别的信件！', 'fr': 'Inscrivez-vous maintenant et commencez à échanger des lettres avec quelqu\'un dans le monde!', 'de': 'Registrieren Sie sich jetzt und tauschen Sie besondere Briefe mit jemandem auf der Welt aus!', 'es': '¡Regístrate ahora y empieza a intercambiar cartas especiales con alguien en el mundo!', 'pt': 'Cadastre-se agora e comece a trocar cartas especiais com alguém no mundo!', 'ru': 'Зарегистрируйтесь сейчас и начните обмениваться особыми письмами с кем-то в мире!', 'tr': 'Şimdi kaydolun ve dünyadaki biriyle özel mektuplar alışverişi yapmaya başlayın!', 'ar': 'سجّل الآن وابدأ تبادل رسائل خاصة مع شخص ما في العالم!', 'it': 'Registrati ora e inizia a scambiare lettere speciali con qualcuno nel mondo!', 'hi': 'अभी साइन अप करें और दुनिया में किसी के साथ विशेष पत्र आदान-प्रदान शुरू करें!', 'th': 'สมัครเดี๋ยวนี้และเริ่มแลกจดหมายพิเศษกับใครบางคนในโลก!'});

  String get getStarted => _t({'ko': '시작하기', 'en': 'Get Started', 'ja': '始める', 'zh': '开始', 'fr': 'Commencer', 'de': 'Loslegen', 'es': 'Comenzar', 'pt': 'Começar', 'ru': 'Начать', 'tr': 'Başla', 'ar': 'ابدأ', 'it': 'Inizia', 'hi': 'शुरू करें', 'th': 'เริ่มต้น'});
  String get skip => _t({'ko': '건너뛰기', 'en': 'Skip', 'ja': 'スキップ', 'zh': '跳过', 'fr': 'Passer', 'de': 'Überspringen', 'es': 'Saltar', 'pt': 'Pular', 'ru': 'Пропустить', 'tr': 'Atla', 'ar': 'تخطي', 'it': 'Salta', 'hi': 'छोड़ें', 'th': 'ข้าม'});

  // ── Account ───────────────────────────────────────────────────────────────
  String get deleteAccount => _t({'ko': '회원탈퇴', 'en': 'Delete Account', 'ja': '退会する', 'zh': '注销账户', 'fr': 'Supprimer le compte', 'de': 'Konto löschen', 'es': 'Eliminar cuenta', 'pt': 'Excluir conta', 'ru': 'Удалить аккаунт', 'tr': 'Hesabı sil', 'ar': 'حذف الحساب', 'it': 'Elimina account', 'hi': 'खाता हटाएं', 'th': 'ลบบัญชี'});
  String get logout => _t({'ko': '로그아웃', 'en': 'Logout', 'ja': 'ログアウト', 'zh': '退出登录', 'fr': 'Déconnexion', 'de': 'Abmelden', 'es': 'Cerrar sesión', 'pt': 'Sair', 'ru': 'Выйти', 'tr': 'Çıkış yap', 'ar': 'تسجيل الخروج', 'it': 'Disconnetti', 'hi': 'लॉगआउट', 'th': 'ออกจากระบบ'});
  String get findId => _t({'ko': '아이디 찾기', 'en': 'Find ID', 'ja': 'IDを探す', 'zh': '找账号', 'fr': 'Trouver l\'ID', 'de': 'ID finden', 'es': 'Encontrar ID', 'pt': 'Encontrar ID', 'ru': 'Найти ID', 'tr': 'ID bul', 'ar': 'إيجاد المعرف', 'it': 'Trova ID', 'hi': 'आईडी खोजें', 'th': 'ค้นหา ID'});
  String get resetPassword => _t({'ko': '비밀번호 찾기', 'en': 'Reset Password', 'ja': 'パスワードを探す', 'zh': '找密码', 'fr': 'Réinitialiser le mot de passe', 'de': 'Passwort zurücksetzen', 'es': 'Restablecer contraseña', 'pt': 'Redefinir senha', 'ru': 'Сбросить пароль', 'tr': 'Şifreyi sıfırla', 'ar': 'إعادة تعيين كلمة المرور', 'it': 'Reimposta password', 'hi': 'पासवर्ड रीसेट करें', 'th': 'รีเซ็ตรหัสผ่าน'});
  String get next => _t({'ko': '다음', 'en': 'Next', 'ja': '次へ', 'zh': '下一步', 'fr': 'Suivant', 'de': 'Weiter', 'es': 'Siguiente', 'pt': 'Próximo', 'ru': 'Далее', 'tr': 'İleri', 'ar': 'التالي', 'it': 'Avanti', 'hi': 'अगला', 'th': 'ถัดไป'});
  String get checking => _t({'ko': '확인 중...', 'en': 'Checking...', 'ja': '確認中...', 'zh': '检查中...', 'fr': 'Vérification...', 'de': 'Prüfung...', 'es': 'Verificando...', 'pt': 'Verificando...', 'ru': 'Проверка...', 'tr': 'Kontrol ediliyor...', 'ar': 'جارٍ التحقق...', 'it': 'Verifica...', 'hi': 'जाँच हो रही है...', 'th': 'กำลังตรวจสอบ...'});
  String get locationAllow => _t({'ko': '위치 허용하기', 'en': 'Allow Location', 'ja': '位置を許可', 'zh': '允许位置', 'fr': 'Autoriser la position', 'de': 'Standort erlauben', 'es': 'Permitir ubicación', 'pt': 'Permitir localização', 'ru': 'Разрешить геолокацию', 'tr': 'Konuma izin ver', 'ar': 'السماح بالموقع', 'it': 'Consenti posizione', 'hi': 'स्थान अनुमति दें', 'th': 'อนุญาตตำแหน่ง'});
  String get locationGranted => _t({'ko': '위치 허용 완료!', 'en': 'Location Allowed!', 'ja': '位置情報を許可しました！', 'zh': '位置已允许！', 'fr': 'Position autorisée !', 'de': 'Standort erlaubt!', 'es': '¡Ubicación permitida!', 'pt': 'Localização permitida!', 'ru': 'Геолокация разрешена!', 'tr': 'Konum izni verildi!', 'ar': 'تم السماح بالموقع!', 'it': 'Posizione consentita!', 'hi': 'स्थान अनुमत है!', 'th': 'อนุญาตตำแหน่งแล้ว!'});
  String get locationRequired => _t({'ko': '내 위치 허용이 필요해요', 'en': 'Location Permission Required', 'ja': '位置情報の許可が必要です', 'zh': '需要位置权限', 'fr': 'Permission de localisation requise', 'de': 'Standortberechtigung erforderlich', 'es': 'Permiso de ubicación requerido', 'pt': 'Permissão de localização necessária', 'ru': 'Необходимо разрешение на геолокацию', 'tr': 'Konum izni gerekli', 'ar': 'إذن الموقع مطلوب', 'it': 'Autorizzazione posizione richiesta', 'hi': 'स्थान अनुमति आवश्यक है', 'th': 'ต้องการอนุญาตตำแหน่ง'});
  String get locationGrantedBody => _t({'ko': '주변 500m 이내에 도착한 편지를\n수령할 수 있어요 🎉', 'en': 'You can receive letters that arrive\nwithin 500m of you 🎉', 'ja': '500m以内に届いた手紙を\n受け取ることができます 🎉', 'zh': '您可以接收到达\n500米范围内的信件 🎉', 'fr': 'Vous pouvez recevoir les lettres\narrivant à 500m de vous 🎉', 'de': 'Sie können Briefe erhalten,\ndie innerhalb 500m ankommen 🎉', 'es': 'Puedes recibir cartas que lleguen\na 500m de ti 🎉', 'pt': 'Você pode receber cartas que chegam\na 500m de você 🎉', 'ru': 'Вы можете получать письма\nв радиусе 500м 🎉', 'tr': '500m içindeki mektupları\nalabilirsiniz 🎉', 'ar': 'يمكنك استلام الرسائل الواصلة\nضمن 500 متر منك 🎉', 'it': 'Puoi ricevere lettere che arrivano\nentro 500m da te 🎉', 'hi': '500मी के भीतर पहुंचने वाले पत्र\nप्राप्त कर सकते हैं 🎉', 'th': 'คุณสามารถรับจดหมายที่มาถึง\nภายใน 500 ม. จากคุณ 🎉'});
  String get locationRequiredBody => _t({'ko': '편지가 내 위치 500m 이내에 도착하면\n알림을 받을 수 있어요.\n위치 정보는 앱 내에서만 사용됩니다.', 'en': 'Get notified when a letter arrives\nwithin 500m of you.\nLocation is only used within the app.', 'ja': '500m以内に手紙が届いたとき\n通知を受け取れます。\n位置情報はアプリ内のみで使用されます。', 'zh': '当信件到达500m范围内时\n您将收到通知。\n位置仅在应用内使用。', 'fr': 'Recevez des notifications lorsqu\'une lettre\narrive à 500m de vous.\nLa position est utilisée uniquement dans l\'app.', 'de': 'Benachrichtigungen wenn ein Brief\ninnerhalb 500m ankommt.\nStandort wird nur in der App verwendet.', 'es': 'Recibe notificaciones cuando llegue una carta\na 500m de ti.\nLa ubicación solo se usa en la app.', 'pt': 'Receba notificações quando uma carta chegar\na 500m de você.\nLocalização usada apenas no app.', 'ru': 'Получайте уведомления когда письмо\nприбывает в 500м.\nГеолокация используется только в приложении.', 'tr': '500m içinde mektup geldiğinde\nbildirim alın.\nKonum yalnızca uygulama içinde kullanılır.', 'ar': 'احصل على إشعار عند وصول رسالة\nضمن 500 متر.\nيُستخدم الموقع داخل التطبيق فقط.', 'it': 'Ricevi notifiche quando una lettera\narriva a 500m da te.\nLa posizione è usata solo nell\'app.', 'hi': 'जब 500मी के भीतर पत्र आए\nतो सूचना पाएं।\nस्थान केवल ऐप में उपयोग होता है।', 'th': 'รับการแจ้งเตือนเมื่อจดหมายมาถึง\nภายใน 500 ม.\nตำแหน่งใช้เฉพาะในแอปเท่านั้น'});
}
